# Generated by Django 6.0.5 on 2026-06-11 13:05

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivelextincao',
            options={'verbose_name': 'Nível de Extinção', 'verbose_name_plural': 'Níveis de Extinção'},
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='criado_por',
            new_name='autor_cad',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='ameacas',
            new_name='obs',
        ),
        migrations.RenameField(
            model_name='bioma',
            old_name='caracteristicas',
            new_name='caract',
        ),
        migrations.AlterUniqueTogether(
            name='regiao',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='animal',
            name='bioma',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='icone_mapa',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='location',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='regiao',
        ),
        migrations.RemoveField(
            model_name='nivelextincao',
            name='ordem_prioridade',
        ),
        migrations.AddField(
            model_name='animal',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='biomas',
            field=models.ManyToManyField(related_name='animais', to='api.bioma'),
        ),
        migrations.AddField(
            model_name='animal',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bioma',
            name='nivel_destr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bioma',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='data_nasc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='denuncias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='animal',
            name='dieta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='familia',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='imagem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nivel_destruicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animais', to='api.niveldestruicao'),
        ),
        migrations.AlterField(
            model_name='nivelextincao',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='nivelextincao',
            name='sigla',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='regiao',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=2, unique=True)),
                ('regiao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='api.regiao')),
            ],
        ),
        migrations.AddField(
            model_name='bioma',
            name='estados',
            field=models.ManyToManyField(related_name='biomas', to='api.estado'),
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('recebedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacoes_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interação',
                'verbose_name_plural': 'Interações',
            },
        ),
        migrations.CreateModel(
            name='Marcador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('icone', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcadores', to='api.animal')),
            ],
            options={
                'verbose_name': 'Marcador',
                'verbose_name_plural': 'Marcadores',
            },
        ),
        migrations.CreateModel(
            name='Microrregiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microrregioes', to='api.estado')),
            ],
            options={
                'verbose_name': 'Microrregião',
                'verbose_name_plural': 'Microrregiões',
                'unique_together': {('nome', 'estado')},
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='microrregiao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animais', to='api.microrregiao'),
        ),
        migrations.RemoveField(
            model_name='regiao',
            name='estado',
        ),
    ]
