# Generated by Django 6.0.5 on 2026-06-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_nivelextincao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='animais/'),
        ),
    ]
