# Generated by Django 6.0.5 on 2026-06-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_animal_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='nome_cientifico',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('nome_cientifico',), name='unique_active_scientific_name'),
        ),
    ]
