# Generated by Django 6.0.5 on 2026-06-15 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_animal_nome_cientifico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='imagem',
            new_name='imagem_principal',
        ),
        migrations.CreateModel(
            name='AnimalImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='animais/extras/')),
                ('legenda', models.CharField(blank=True, max_length=100, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_adicionais', to='api.animal')),
            ],
            options={
                'verbose_name': 'Imagem Adicional',
                'verbose_name_plural': 'Imagens Adicionais',
                'ordering': ['ordem'],
            },
        ),
    ]
