# Generated by Django 6.0.5 on 2026-06-15 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_imagem_animal_imagem_principal_animalimagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalimagem',
            options={'ordering': ['ordem'], 'verbose_name': 'Imagem do Animal', 'verbose_name_plural': 'Imagens dos Animais'},
        ),
        migrations.RemoveField(
            model_name='animal',
            name='imagem_principal',
        ),
        migrations.AlterField(
            model_name='animalimagem',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='api.animal'),
        ),
        migrations.AlterField(
            model_name='animalimagem',
            name='imagem',
            field=models.ImageField(upload_to='animais/'),
        ),
    ]
