# Generated by Django 6.0.5 on 2026-08-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_favorito_delete_interacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalimagem',
            name='imagem',
            field=models.CharField(max_length=500),
        ),
    ]
