CREATE EXTENSION IF NOT EXISTS postgis;

--
-- PostgreSQL database dump
--

\restrict bIdmO6M12jQYlGSr4tDKAYqXO044iJfiyehcKlpXNChCxBFfrd4MLHCKd6OXlK3

-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS '';


--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: api_animal; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_animal (
    id bigint NOT NULL,
    deleted_at timestamp with time zone,
    nome_comum character varying(100) NOT NULL,
    nome_cientifico character varying(150) NOT NULL,
    classe character varying(50),
    familia character varying(70),
    dieta character varying(50),
    habitos text,
    obs text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    autor_cad_id bigint,
    nivel_destruicao_id bigint,
    nivel_extincao_id bigint NOT NULL,
    altura double precision,
    peso double precision,
    microrregiao_id bigint
);


ALTER TABLE public.api_animal OWNER TO postgres;

--
-- Name: api_animal_biomas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_animal_biomas (
    id bigint NOT NULL,
    animal_id bigint NOT NULL,
    bioma_id bigint NOT NULL
);


ALTER TABLE public.api_animal_biomas OWNER TO postgres;

--
-- Name: api_animal_biomas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_animal_biomas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_animal_biomas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_animal_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_animal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_animal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_animalimagem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_animalimagem (
    id bigint NOT NULL,
    imagem character varying(100) NOT NULL,
    legenda character varying(100),
    ordem integer NOT NULL,
    animal_id bigint NOT NULL,
    CONSTRAINT api_animalimagem_ordem_check CHECK ((ordem >= 0))
);


ALTER TABLE public.api_animalimagem OWNER TO postgres;

--
-- Name: api_animalimagem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_animalimagem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_animalimagem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_bioma; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_bioma (
    id bigint NOT NULL,
    nome character varying(100) NOT NULL,
    caract text,
    nivel_destr character varying(100),
    tipo character varying(100)
);


ALTER TABLE public.api_bioma OWNER TO postgres;

--
-- Name: api_bioma_estados; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_bioma_estados (
    id bigint NOT NULL,
    bioma_id bigint NOT NULL,
    estado_id bigint NOT NULL
);


ALTER TABLE public.api_bioma_estados OWNER TO postgres;

--
-- Name: api_bioma_estados_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_bioma_estados ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_bioma_estados_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_bioma_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_bioma ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_bioma_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_estado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_estado (
    id bigint NOT NULL,
    nome character varying(50) NOT NULL,
    sigla character varying(2) NOT NULL,
    regiao_id bigint
);


ALTER TABLE public.api_estado OWNER TO postgres;

--
-- Name: api_estado_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_estado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_estado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_favorito; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_favorito (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    animal_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.api_favorito OWNER TO postgres;

--
-- Name: api_favorito_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_favorito ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_favorito_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_marcador; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_marcador (
    id bigint NOT NULL,
    location public.geometry(Point,4326) NOT NULL,
    icone text,
    created_at timestamp with time zone NOT NULL,
    animal_id bigint NOT NULL
);


ALTER TABLE public.api_marcador OWNER TO postgres;

--
-- Name: api_marcador_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_marcador ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_marcador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_microrregiao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_microrregiao (
    id bigint NOT NULL,
    nome character varying(100) NOT NULL,
    estado_id bigint NOT NULL
);


ALTER TABLE public.api_microrregiao OWNER TO postgres;

--
-- Name: api_microrregiao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_microrregiao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_microrregiao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_niveldestruicao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_niveldestruicao (
    id bigint NOT NULL,
    nome character varying(100) NOT NULL,
    descricao text,
    cor_alerta character varying(7) NOT NULL
);


ALTER TABLE public.api_niveldestruicao OWNER TO postgres;

--
-- Name: api_niveldestruicao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_niveldestruicao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_niveldestruicao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_nivelextincao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_nivelextincao (
    id bigint NOT NULL,
    sigla character varying(5),
    nome character varying(100) NOT NULL,
    descricao text
);


ALTER TABLE public.api_nivelextincao OWNER TO postgres;

--
-- Name: api_nivelextincao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_nivelextincao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_nivelextincao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_ong; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_ong (
    id bigint NOT NULL,
    deleted_at timestamp with time zone,
    nome character varying(150) NOT NULL,
    descricao text,
    email character varying(100),
    telefone character varying(20),
    site character varying(200),
    location public.geometry(Point,4326) NOT NULL,
    endereco text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.api_ong OWNER TO postgres;

--
-- Name: api_ong_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_ong ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_ong_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_regiao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_regiao (
    id bigint NOT NULL,
    nome character varying(100) NOT NULL
);


ALTER TABLE public.api_regiao OWNER TO postgres;

--
-- Name: api_regiao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_regiao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_regiao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(20) NOT NULL,
    deleted_at timestamp with time zone,
    data_nasc date,
    denuncias integer NOT NULL
);


ALTER TABLE public.api_user OWNER TO postgres;

--
-- Name: api_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.api_user_groups OWNER TO postgres;

--
-- Name: api_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.api_user_user_permissions OWNER TO postgres;

--
-- Name: api_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_zonapreservacao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_zonapreservacao (
    id bigint NOT NULL,
    deleted_at timestamp with time zone,
    nome character varying(150) NOT NULL,
    descricao text,
    categoria character varying(100),
    area public.geometry(MultiPolygon,4326) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.api_zonapreservacao OWNER TO postgres;

--
-- Name: api_zonapreservacao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_zonapreservacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_zonapreservacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: api_animal_biomas api_animal_biomas_animal_id_bioma_id_d8b7ec0e_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_animal_biomas
    ADD CONSTRAINT api_animal_biomas_animal_id_bioma_id_d8b7ec0e_uniq UNIQUE (animal_id, bioma_id);


--
-- Name: api_animal_biomas api_animal_biomas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_animal_biomas
    ADD CONSTRAINT api_animal_biomas_pkey PRIMARY KEY (id);


--
-- Name: api_animal api_animal_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_animal
    ADD CONSTRAINT api_animal_pkey PRIMARY KEY (id);


--
-- Name: api_animalimagem api_animalimagem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_animalimagem
    ADD CONSTRAINT api_animalimagem_pkey PRIMARY KEY (id);


--
-- Name: api_bioma_estados api_bioma_estados_bioma_id_estado_id_54f91621_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_bioma_estados
    ADD CONSTRAINT api_bioma_estados_bioma_id_estado_id_54f91621_uniq UNIQUE (bioma_id, estado_id);


--
-- Name: api_bioma_estados api_bioma_estados_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_bioma_estados
    ADD CONSTRAINT api_bioma_estados_pkey PRIMARY KEY (id);


--
-- Name: api_bioma api_bioma_nome_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_bioma
    ADD CONSTRAINT api_bioma_nome_key UNIQUE (nome);


--
-- Name: api_bioma api_bioma_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_bioma
    ADD CONSTRAINT api_bioma_pkey PRIMARY KEY (id);


--
-- Name: api_estado api_estado_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_estado
    ADD CONSTRAINT api_estado_pkey PRIMARY KEY (id);


--
-- Name: api_estado api_estado_sigla_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_estado
    ADD CONSTRAINT api_estado_sigla_key UNIQUE (sigla);


--
-- Name: api_favorito api_favorito_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_favorito
    ADD CONSTRAINT api_favorito_pkey PRIMARY KEY (id);


--
-- Name: api_favorito api_favorito_user_id_animal_id_f457eda5_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_favorito
    ADD CONSTRAINT api_favorito_user_id_animal_id_f457eda5_uniq UNIQUE (user_id, animal_id);


--
-- Name: api_marcador api_marcador_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_marcador
    ADD CONSTRAINT api_marcador_pkey PRIMARY KEY (id);


--
-- Name: api_microrregiao api_microrregiao_nome_estado_id_930f23a7_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_microrregiao
    ADD CONSTRAINT api_microrregiao_nome_estado_id_930f23a7_uniq UNIQUE (nome, estado_id);


--
-- Name: api_microrregiao api_microrregiao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_microrregiao
    ADD CONSTRAINT api_microrregiao_pkey PRIMARY KEY (id);


--
-- Name: api_niveldestruicao api_niveldestruicao_nome_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_niveldestruicao
    ADD CONSTRAINT api_niveldestruicao_nome_key UNIQUE (nome);


--
-- Name: api_niveldestruicao api_niveldestruicao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_niveldestruicao
    ADD CONSTRAINT api_niveldestruicao_pkey PRIMARY KEY (id);


--
-- Name: api_nivelextincao api_nivelextincao_nome_31220dde_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_nivelextincao
    ADD CONSTRAINT api_nivelextincao_nome_31220dde_uniq UNIQUE (nome);


--
-- Name: api_nivelextincao api_nivelextincao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_nivelextincao
    ADD CONSTRAINT api_nivelextincao_pkey PRIMARY KEY (id);


--
-- Name: api_ong api_ong_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_ong
    ADD CONSTRAINT api_ong_pkey PRIMARY KEY (id);


--
-- Name: api_regiao api_regiao_nome_767174d3_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_regiao
    ADD CONSTRAINT api_regiao_nome_767174d3_uniq UNIQUE (nome);


--
-- Name: api_regiao api_regiao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_regiao
    ADD CONSTRAINT api_regiao_pkey PRIMARY KEY (id);


--
-- Name: api_user_groups api_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_user_groups
    ADD CONSTRAINT api_user_groups_pkey PRIMARY KEY (id);


--
-- Name: api_user_groups api_user_groups_user_id_group_id_9c7ddfb5_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_user_groups
    ADD CONSTRAINT api_user_groups_user_id_group_id_9c7ddfb5_uniq UNIQUE (user_id, group_id);


--
-- Name: api_user api_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_user
    ADD CONSTRAINT api_user_pkey PRIMARY KEY (id);


--
-- Name: api_user_user_permissions api_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_user_user_permissions
    ADD CONSTRAINT api_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: api_user_user_permissions api_user_user_permissions_user_id_permission_id_a06dd704_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_user_user_permissions
    ADD CONSTRAINT api_user_user_permissions_user_id_permission_id_a06dd704_uniq UNIQUE (user_id, permission_id);


--
-- Name: api_user api_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_user
    ADD CONSTRAINT api_user_username_key UNIQUE (username);


--
-- Name: api_zonapreservacao api_zonapreservacao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_zonapreservacao
    ADD CONSTRAINT api_zonapreservacao_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: api_animal_biomas_animal_id_bc96b8f6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_animal_biomas_animal_id_bc96b8f6 ON public.api_animal_biomas USING btree (animal_id);


--
-- Name: api_animal_biomas_bioma_id_8f49162c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_animal_biomas_bioma_id_8f49162c ON public.api_animal_biomas USING btree (bioma_id);


--
-- Name: api_animal_criado_por_id_60e22694; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_animal_criado_por_id_60e22694 ON public.api_animal USING btree (autor_cad_id);


--
-- Name: api_animal_microrregiao_id_9381e61d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_animal_microrregiao_id_9381e61d ON public.api_animal USING btree (microrregiao_id);


--
-- Name: api_animal_nivel_destruicao_id_bd962333; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_animal_nivel_destruicao_id_bd962333 ON public.api_animal USING btree (nivel_destruicao_id);


--
-- Name: api_animal_nivel_extincao_id_cd92a08b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_animal_nivel_extincao_id_cd92a08b ON public.api_animal USING btree (nivel_extincao_id);


--
-- Name: api_animalimagem_animal_id_77468e03; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_animalimagem_animal_id_77468e03 ON public.api_animalimagem USING btree (animal_id);


--
-- Name: api_bioma_estados_bioma_id_19ec907a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_bioma_estados_bioma_id_19ec907a ON public.api_bioma_estados USING btree (bioma_id);


--
-- Name: api_bioma_estados_estado_id_62a82e1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_bioma_estados_estado_id_62a82e1b ON public.api_bioma_estados USING btree (estado_id);


--
-- Name: api_bioma_nome_0d6095b7_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_bioma_nome_0d6095b7_like ON public.api_bioma USING btree (nome varchar_pattern_ops);


--
-- Name: api_estado_regiao_id_cea44c07; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_estado_regiao_id_cea44c07 ON public.api_estado USING btree (regiao_id);


--
-- Name: api_estado_sigla_c4ec2fe6_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_estado_sigla_c4ec2fe6_like ON public.api_estado USING btree (sigla varchar_pattern_ops);


--
-- Name: api_favorito_animal_id_8ca07508; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_favorito_animal_id_8ca07508 ON public.api_favorito USING btree (animal_id);


--
-- Name: api_favorito_user_id_a4ba5d82; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_favorito_user_id_a4ba5d82 ON public.api_favorito USING btree (user_id);


--
-- Name: api_marcador_animal_id_da3463ec; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_marcador_animal_id_da3463ec ON public.api_marcador USING btree (animal_id);


--
-- Name: api_marcador_location_fb82ded9_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_marcador_location_fb82ded9_id ON public.api_marcador USING gist (location);


--
-- Name: api_microrregiao_estado_id_c7224df3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_microrregiao_estado_id_c7224df3 ON public.api_microrregiao USING btree (estado_id);


--
-- Name: api_niveldestruicao_nome_d03b5b09_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_niveldestruicao_nome_d03b5b09_like ON public.api_niveldestruicao USING btree (nome varchar_pattern_ops);


--
-- Name: api_nivelextincao_nome_31220dde_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_nivelextincao_nome_31220dde_like ON public.api_nivelextincao USING btree (nome varchar_pattern_ops);


--
-- Name: api_ong_location_7582b4fd_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_ong_location_7582b4fd_id ON public.api_ong USING gist (location);


--
-- Name: api_regiao_nome_767174d3_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_regiao_nome_767174d3_like ON public.api_regiao USING btree (nome varchar_pattern_ops);


--
-- Name: api_user_groups_group_id_3af85785; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_user_groups_group_id_3af85785 ON public.api_user_groups USING btree (group_id);


--
-- Name: api_user_groups_user_id_a5ff39fa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_user_groups_user_id_a5ff39fa ON public.api_user_groups USING btree (user_id);


--
-- Name: api_user_user_permissions_permission_id_305b7fea; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_user_user_permissions_permission_id_305b7fea ON public.api_user_user_permissions USING btree (permission_id);


--
-- Name: api_user_user_permissions_user_id_f3945d65; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_user_user_permissions_user_id_f3945d65 ON public.api_user_user_permissions USING btree (user_id);


--
-- Name: api_user_username_cf4e88d2_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_user_username_cf4e88d2_like ON public.api_user USING btree (username varchar_pattern_ops);


--
-- Name: api_zonapreservacao_area_de95f3be_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_zonapreservacao_area_de95f3be_id ON public.api_zonapreservacao USING gist (area);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: unique_active_scientific_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX unique_active_scientific_name ON public.api_animal USING btree (nome_cientifico) WHERE (deleted_at IS NULL);


--
-- Name: api_animal api_animal_autor_cad_id_9ef37c4a_fk_api_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_animal
    ADD CONSTRAINT api_animal_autor_cad_id_9ef37c4a_fk_api_user_id FOREIGN KEY (autor_cad_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_animal_biomas api_animal_biomas_animal_id_bc96b8f6_fk_api_animal_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_animal_biomas
    ADD CONSTRAINT api_animal_biomas_animal_id_bc96b8f6_fk_api_animal_id FOREIGN KEY (animal_id) REFERENCES public.api_animal(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_animal_biomas api_animal_biomas_bioma_id_8f49162c_fk_api_bioma_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_animal_biomas
    ADD CONSTRAINT api_animal_biomas_bioma_id_8f49162c_fk_api_bioma_id FOREIGN KEY (bioma_id) REFERENCES public.api_bioma(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_animal api_animal_microrregiao_id_9381e61d_fk_api_microrregiao_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_animal
    ADD CONSTRAINT api_animal_microrregiao_id_9381e61d_fk_api_microrregiao_id FOREIGN KEY (microrregiao_id) REFERENCES public.api_microrregiao(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_animal api_animal_nivel_destruicao_id_bd962333_fk_api_nivel; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_animal
    ADD CONSTRAINT api_animal_nivel_destruicao_id_bd962333_fk_api_nivel FOREIGN KEY (nivel_destruicao_id) REFERENCES public.api_niveldestruicao(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_animal api_animal_nivel_extincao_id_cd92a08b_fk_api_nivelextincao_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_animal
    ADD CONSTRAINT api_animal_nivel_extincao_id_cd92a08b_fk_api_nivelextincao_id FOREIGN KEY (nivel_extincao_id) REFERENCES public.api_nivelextincao(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_animalimagem api_animalimagem_animal_id_77468e03_fk_api_animal_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_animalimagem
    ADD CONSTRAINT api_animalimagem_animal_id_77468e03_fk_api_animal_id FOREIGN KEY (animal_id) REFERENCES public.api_animal(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_bioma_estados api_bioma_estados_bioma_id_19ec907a_fk_api_bioma_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_bioma_estados
    ADD CONSTRAINT api_bioma_estados_bioma_id_19ec907a_fk_api_bioma_id FOREIGN KEY (bioma_id) REFERENCES public.api_bioma(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_bioma_estados api_bioma_estados_estado_id_62a82e1b_fk_api_estado_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_bioma_estados
    ADD CONSTRAINT api_bioma_estados_estado_id_62a82e1b_fk_api_estado_id FOREIGN KEY (estado_id) REFERENCES public.api_estado(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_estado api_estado_regiao_id_cea44c07_fk_api_regiao_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_estado
    ADD CONSTRAINT api_estado_regiao_id_cea44c07_fk_api_regiao_id FOREIGN KEY (regiao_id) REFERENCES public.api_regiao(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_favorito api_favorito_animal_id_8ca07508_fk_api_animal_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_favorito
    ADD CONSTRAINT api_favorito_animal_id_8ca07508_fk_api_animal_id FOREIGN KEY (animal_id) REFERENCES public.api_animal(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_favorito api_favorito_user_id_a4ba5d82_fk_api_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_favorito
    ADD CONSTRAINT api_favorito_user_id_a4ba5d82_fk_api_user_id FOREIGN KEY (user_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_marcador api_marcador_animal_id_da3463ec_fk_api_animal_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_marcador
    ADD CONSTRAINT api_marcador_animal_id_da3463ec_fk_api_animal_id FOREIGN KEY (animal_id) REFERENCES public.api_animal(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_microrregiao api_microrregiao_estado_id_c7224df3_fk_api_estado_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_microrregiao
    ADD CONSTRAINT api_microrregiao_estado_id_c7224df3_fk_api_estado_id FOREIGN KEY (estado_id) REFERENCES public.api_estado(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_user_groups api_user_groups_group_id_3af85785_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_user_groups
    ADD CONSTRAINT api_user_groups_group_id_3af85785_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_user_groups api_user_groups_user_id_a5ff39fa_fk_api_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_user_groups
    ADD CONSTRAINT api_user_groups_user_id_a5ff39fa_fk_api_user_id FOREIGN KEY (user_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_user_user_permissions api_user_user_permis_permission_id_305b7fea_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_user_user_permissions
    ADD CONSTRAINT api_user_user_permis_permission_id_305b7fea_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_user_user_permissions api_user_user_permissions_user_id_f3945d65_fk_api_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_user_user_permissions
    ADD CONSTRAINT api_user_user_permissions_user_id_f3945d65_fk_api_user_id FOREIGN KEY (user_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_api_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_api_user_id FOREIGN KEY (user_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

\unrestrict bIdmO6M12jQYlGSr4tDKAYqXO044iJfiyehcKlpXNChCxBFfrd4MLHCKd6OXlK3

