name: Sincronizar Fork Automaticamente

on:
  schedule:
    - cron: '*/15 * * * *' # Roda a cada 15 minutos
  workflow_dispatch: # Permite rodar manualmente se precisar

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Sincronizando com o original
        run: gh repo sync ${{ github.repository }} --branch main
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN || secrets.GITHUB_TOKEN }}

